### ISSUE TITLE
battle count mismatch

### ISSUE THREAD

**Issue by paul-sama** [spacemeowx2/s3si.ts#12]
<img width="231" alt="image" src="https://user-images.githubusercontent.com/350651/199521174-c7d62e4d-6ba0-41ae-a1f3-cac778a9d7d5.png">

**Comment by spacemeowx2** [comment]
Currently only successful export processes are counted (token expires cause it to fail), and fixing this may require a large part of the change. If you have any urgent needs I will raise the priority of this issue.

**Comment by spacemeowx2** [comment]
nvm, I found I can print count after error.

**Comment by paul-sama** [comment]
![image](https://user-images.githubusercontent.com/350651/201622764-6d9fabb9-5d72-45c9-bcf1-a0d41b08f2bb.png)

**Comment by spacemeowx2** [comment]
tri-color battle is not supported by stat.ink. so it marked as export but actually skipped. should be fixed once stat.ink supports tri-color export

**Comment by spacemeowx2** [comment]
Added a new type of output: Skip. The result should be correct now.
