### ISSUE TITLE
[feature request] collect general player data/stats for external usage

### ISSUE THREAD

**Issue by lowlighter** [spacemeowx2/s3si.ts#26]
First, thanks a lot for this awesome tool !
I really like how it's straightforward to use and the fact it's written for deno 😄 

I know this tool is mostly intended to export match data to stat.ink, but do you think it could be possible to also provide additional CLI options to fetch other data for the file exporter ? 

I'm mostly thinking about weapons stats and badges, but I guess festivals teams or favorites gears could be cool too.
Some sections on the splatnet app offer a lot of data and it'd be nice to be able to use them:

<img src="https://user-images.githubusercontent.com/22963968/203196226-0d41baf7-0b8e-4134-b77b-d34b2d416a74.png" width="200"><img src="https://user-images.githubusercontent.com/22963968/203196249-dc6c67dc-36a0-42ce-ab37-09a3db711934.png" width="200">

**Context:**

I'm currently using s3si.ts output to render SVG badges of last played matches through GitHub Actions (see example below, may be a bit buggy on mobile though), and the aim would be to display more general data to make some kind of player card 😄 

<img width="380" src="https://raw.githubusercontent.com/lowlighter/metrics/examples/metrics.plugin.splatoon.svg">

**Comment by spacemeowx2** [comment]
Glad you like the tool! You've designed a great looking svg, I love it!


It's a great idea, and there may be a need for it with other potential export targets.
