### ISSUE TITLE
Error: Weapon not found: 熊先生印章防空伞

### ISSUE THREAD

**Issue by paul-sama** [spacemeowx2/s3si.ts#27]
Error: Weapon not found: 熊先生印章防空伞

**Comment by paul-sama** [comment]
Error: Weapon not found: 随机

**Comment by paul-sama** [comment]
```
Cannot read properties of null (reading 'id')
        SPLATNET3_STATINK_MAP.COOP_SPECIAL_MAP[b64Number(specialWeapon.id)],
```

**Comment by spacemeowx2** [comment]
Hi, can you send me your file export folder to debug? I can't see `随机` or null `specialWeapon` in my data.

Run `s3si.ts` with `-e file -s vs` to export salmon run battles to file.
