### ISSUE TITLE
salmon missing some infomation

### ISSUE THREAD

**Issue by paul-sama** [spacemeowx2/s3si.ts#28]
**Describe the bug**
missing Salmometer and title

<img width="674" alt="image" src="https://user-images.githubusercontent.com/350651/203980910-72620238-c2c4-4db9-ab2b-1762086872c4.png">

<img width="758" alt="image" src="https://user-images.githubusercontent.com/350651/203981102-ef85f5f6-e4d2-4b3c-9062-f1f5e7d8f890.png">

**Comment by spacemeowx2** [comment]
Should be fixed. Thank you for reporting!

**Comment by spacemeowx2** [comment]
Just added a script to wipe out all salmon run battles on stat.ink: https://github.com/spacemeowx2/s3si.ts/blob/main/scripts/delete-coop.ts
