### ISSUE TITLE
Duplicate uploads of Salmon Run jobs previously uploaded by s3s

### ISSUE THREAD

**Issue by AAGaming00** [spacemeowx2/s3si.ts#45]
**Describe the bug**
I've been running s3s for the past few weeks, and wanted to give s3si.ts a go for its rank tracking. After starting the docker container, I noticed it started trying to upload **50** salmon run jobs, and after stopping it and checking one, I had noticed that it was uploading duplicates of jobs s3s had uploaded.

This can be observed on my stat.ink profile [here](https://stat.ink/@AAGaming/salmon3)

Interestingly, those uploaded by s3si.ts also seem to be missing the rank before (showing ? -> whatever rank whereas s3s shows the data, possibly related to the below error?), and are missing the weapon list on the [Salmon Log](https://stat.ink/@AAGaming/salmon3) page, but not in the full details page.

At some point, I also started getting spam of the following error:

	Body:  { error: { title_exp_before: "Title Exp Before must be no less than 0." } }
	Failed to export to stat.ink: Error: Failed to export battle
	    at StatInkAPI.postCoop (file:///app/src/exporters/stat.ink.ts:136:13)
	    at async StatInkExporter.exportGame (file:///app/src/exporters/stat.ink.ts:294:23)
	    at async step (file:///app/src/app.ts:372:22)
	    at async App.exportGameList (file:///app/src/app.ts:394:9)
	Exported stat.ink: 0
	    at async showError (file:///app/src/utils.ts:75:12)
	    at async Promise.all (index 0)
	    at async App.exportOnce (file:///app/src/app.ts:231:7)
	    at async App.monitor (file:///app/src/app.ts:296:7)
	    at async App.run (file:///app/src/app.ts:332:7)
	    at async showError (file:///app/src/utils.ts:75:12)

I am unsure if this happens with normal games too as I quickly killed s3si.ts after noticing this

**To Reproduce**
1. Use s3s to upload some salmon run jobs
2. Run s3si
3. Notice logs showing duplicated salmon run uploads
4. See these uploaded on stat.ink

**Expected behavior**
s3si.ts should skip jobs uploaded by s3s.

**Screenshots or Links**
If applicable, add screenshots or links to stat.ink to help explain your problem.

**Environment (please complete the following information):**
 - OS: Linux (Docker on arm64 using this repo's Dockerfile modified to use LukeChannings's [deno-arm64](https://github.com/LukeChannings/deno-arm64) images)
 - Deno version 1.26.2
 - Version [0c916cc](https://github.com/spacemeowx2/s3si.ts/commit/0c916cc9e83d469a500b479912288998574bb723)

**Comment by spacemeowx2** [comment]
https://github.com/frozenpandaman/s3s/issues/79

It was a bug in s3s, and I am happy to add workaround to avoid duplicate export

**Comment by spacemeowx2** [comment]
For the second question, in the case of +20 -> 40 it is possible to promote (?). -> 40) or not (20 -> 40). Since context-based judgments have not been added yet, s3si.ts left it blank here. The s3s choice to assume that you always go from 20 -> 40, so there is a chance of inaccuracy.

![image](https://user-images.githubusercontent.com/8019167/204742866-8bec7cc3-c121-4c97-952c-c657d45b44c6.png)
