### ISSUE TITLE
[ERROR] No idToken2 or coralUserId found. Please try again later. ('undefined', 'undefined')

### ISSUE THREAD

**Issue by SicariusREAL** [spacemeowx2/s3si.ts#77]

**Comment by catgirlinspace** [comment]
is s3si.ts up to date?

**Comment by SicariusREAL** [comment]
yes

**Comment by catgirlinspace** [comment]
ah, i think i see the issue maybe. 

@spacemeowx2 the latest release ([v0.4.2](https://github.com/spacemeowx2/s3si.ts/releases/tag/gui-v0.4.2)) doesn't contain the commit a67bb48 and [Nintendo is requiring 2.5.2](https://github.com/samuelthomas2774/nxapi/issues/70).

**Comment by spacemeowx2** [comment]
Sorry for the late reply/fix. I've been sick lately so haven't been able to get around to dealing with this.

https://github.com/spacemeowx2/s3si.ts/releases/tag/gui-v0.4.5 gui-v0.4.5 has been release. Please upgrade the version

**Comment by catgirlinspace** [comment]
@spacemeowx2 hope you feel better soon!! being sick is never fun :(
