### ISSUE TITLE
judgement "DRAW"

### ISSUE THREAD

**Issue by paul-sama** [spacemeowx2/s3si.ts#8]
`judgement: "LOSE" | "WIN" | "DEEMED_LOSE" | "EXEMPTED_LOSE";`
missing `"DRAW"` ? there are five type of judgement

**Comment by spacemeowx2** [comment]
Thanks for pointing out!

**Comment by spacemeowx2** [comment]
Tips: you can delete the wrong battle uploaded to stat.ink by executing `deno run -A ./scripts/delete.ts <STAT_INK_TOKEN> <UUID_IN_URL>`
