### ISSUE TITLE
Cannot Export Stats

### ISSUE THREAD

**Issue by MrPeeperNumber** [spacemeowx2/s3si.ts#82]
**Describe the bug**
Recently, whenever I try to export my stats, I get the error "Cannot read properties of undefined (reading 'length')." I tried resetting my settings, relogging in to my Nintendo account for an account session token, regenerating my stat.ink API, and completely uninstalling the app, but the error persists. It was working for a while, then randomly stopped, and I'm unsure why.

**To Reproduce**
Unknown

**Expected behavior**
To be able to export my stats.

**Screenshots or Links**
![image](https://github.com/spacemeowx2/s3si.ts/assets/37354997/72d8ecd9-1c4d-47da-927b-7b15df61b4a5)

**Environment (please complete the following information):**
 - OS: Win 10
 - Version 0.4.5

**Comment by spacemeowx2** [comment]
Could you please re-try with latest version 0.4.6? I think this version should fix this.

**Comment by MrPeeperNumber** [comment]
It seems to be working now. Thank you the quick fix! :)
