### ISSUE TITLE
Failure to export VS matches (possibly because of the latest Challenge?)

### ISSUE THREAD

**Issue by Tudikun** [spacemeowx2/s3si.ts#85]
**Describe the bug**
Failure to export VS matches. s3si appears to have an issue with the "Sheldon's Dress-Up Showdown" Challenge (random weapons and gear). Salmon Run shifts upload as expected when choosing to skip VS match exporting.

**To Reproduce**
1. Click "Export" in s3si-ts.exe OR run "deno run -Ar https://raw.githubusercontent.com/spacemeowx2/s3si.ts/main/s3si.ts" in the command line.
2. See error

**Expected behavior**
Exporting VS matches to stat.ink with no error.

**Screenshots or Links**
![s3si error](https://github.com/spacemeowx2/s3si.ts/assets/73622196/1b623853-d536-4dcf-8084-7e89e0460afe)

**Environment (please complete the following information):**
 - OS: Windows 10 Pro (Build 19044.3086)
 - Deno version 1.37.2
 - Version v0.4.9

**Additional context**
The aforementioned Challenge grants you a random weapon and set of matching amiibo gear with the original primary abilities and no sub abilities.

**Comment by spacemeowx2** [comment]
Should be fixed

**Comment by Tudikun** [comment]
Works like a charm, thank you!
