### ISSUE TITLE
Cannot initialize on Windows

### ISSUE THREAD

**Issue by solitonmedic** [spacemeowx2/s3si.ts#91]
**Describe the bug**
s3si.ts failed to set-up properly, failed to read API.

**To Reproduce**
1. Install deno through website.
2. Run `deno run -Ar https://raw.githubusercontent.com/spacemeowx2/s3si.ts/main/s3si.ts [options]`
3. Follow on screen

**Expected behavior**
Proceed to the next step in setup.

**Screenshots or Links**
If applicable, add screenshots or links to stat.ink to help explain your problem.

<img width="982" alt="298251994-55649558-f8c1-45f3-9866-8f7c9c82369b" src="https://github.com/spacemeowx2/s3si.ts/assets/14916963/14af942d-6540-4d2a-a418-99d8047210c7">

**Environment (please complete the following information):**
 - OS: Windows 11
 - Deno version: 1.39.4
 - Version: 0.4.12

**Additional context**

**Comment by spacemeowx2** [comment]
Thank you for submitting the issue. It should have been fixed. Please try re-initializing it.
